/**
 * Eight pillars — single source of truth for Programs list, nav, and detail pages.
 */
export const PROGRAMS = [
  {
    id: 'village-development',
    slug: 'village-development',
    title: 'Village Development',
    icon: '🏘️',
    serviceKey: 'village',
    color: 'bg-service-village',
    lightColor: 'bg-service-village-tint',
    textColor: 'text-service-village',
    borderColor: 'border-service-village',
    heroImage: '/hero/village.jpg',
    cover: '/hero/village.jpg',
    description: 'Comprehensive infrastructure improvement for rural villages including roads, public buildings, sanitation, and community facilities.',
    longDescription: 'CMSR connects citizens across India to transform villages through roads, electricity, sanitation, community halls, and digital connectivity — building self-reliant rural communities.',
    impact: ['500+ roads improved', '1,200+ villages covered', '₹8Cr invested'],
    objectives: ['Pucca roads and street lighting', 'Public building renovation', 'Sanitation and drainage', 'Electricity and connectivity', 'Community facility development'],
    activities: ['Road construction & repair', 'Public building renovation', 'Sanitation facilities', 'Electricity connection', 'Street lighting', 'Digital gram sabha'],
    stats: { villages: 1200, schools: 450, volunteers: 8500, donations: 80000000 },
    stories: [
      { title: 'Medaram Village Transformation', desc: 'Complete road and sanitation upgrade benefiting 2,400 residents.', img: '/hero/village.jpg' },
    ],
  },
  {
    id: 'school-empowerment',
    slug: 'school-empowerment',
    title: 'School Empowerment',
    icon: '🏫',
    serviceKey: 'school',
    color: 'bg-service-school',
    lightColor: 'bg-service-school-tint',
    textColor: 'text-service-school',
    borderColor: 'border-service-school',
    heroImage: '/hero/school.jpg',
    cover: '/hero/school.jpg',
    description: 'Empowering rural schools with modern infrastructure, digital resources, and quality education materials.',
    longDescription: 'From digital classrooms to libraries and labs — we upgrade government schools so every rural child gets quality education with modern tools and trained teachers.',
    impact: ['450+ schools supported', '1.5L+ students benefited', '₹4.2Cr invested'],
    objectives: ['Digital classroom setup', 'Library and lab establishment', 'Furniture and equipment', 'Teacher training programs', 'Scholarship support'],
    activities: ['Smart classroom deployment', 'Library establishment', 'Furniture & equipment', 'Teacher training', 'Computer labs', 'STEM workshops'],
    stats: { villages: 450, schools: 450, volunteers: 3200, donations: 42000000 },
    stories: [
      { title: 'CMSR Digital Classroom', desc: 'Tablets and smart boards deployed — 350 students now learn with digital tools.', img: '/hero/school.jpg' },
    ],
  },
  {
    id: 'tree-plantation',
    slug: 'tree-plantation',
    title: 'Tree Plantation',
    icon: '🌳',
    serviceKey: 'tree',
    color: 'bg-service-tree',
    lightColor: 'bg-service-tree-tint',
    textColor: 'text-service-tree',
    borderColor: 'border-service-tree',
    heroImage: '/hero/tree.jpg',
    cover: '/hero/tree.jpg',
    description: 'Massive tree plantation drives to create greener villages and combat climate change.',
    longDescription: 'Planting native and fruit-bearing trees across village boundaries, schools, and common lands — creating green cover and sustainable livelihoods.',
    impact: ['50,000+ trees planted', '320 villages greened', 'CO2 reduction tracked'],
    objectives: ['Mass plantation drives', 'Fruit tree distribution', 'Forest conservation', 'School garden projects', 'Community maintenance'],
    activities: ['Mass plantation drives', 'Fruit tree distribution', 'Forest conservation', 'Village boundary planting', 'School garden projects'],
    stats: { villages: 320, schools: 180, volunteers: 12000, donations: 15000000 },
    stories: [
      { title: 'Green Village Drive', desc: '5,000 saplings planted across 12 villages in one season.', img: '/hero/tree.jpg' },
    ],
  },
  {
    id: 'water-conservation',
    slug: 'water-conservation',
    title: 'Water Conservation',
    icon: '💧',
    serviceKey: 'water',
    color: 'bg-service-water',
    lightColor: 'bg-service-water-tint',
    textColor: 'text-service-water',
    borderColor: 'border-service-water',
    heroImage: '/hero/water.jpg',
    cover: '/hero/water.jpg',
    description: 'Ensuring water security for rural communities through conservation, harvesting, and groundwater recharge.',
    longDescription: 'Check dams, bore wells, rainwater harvesting, and pond restoration — ensuring every village has reliable access to clean water year-round.',
    impact: ['320 water projects', '8,500 farmers helped', '40+ bore wells'],
    objectives: ['Check dam construction', 'Rainwater harvesting', 'Groundwater recharge', 'Pipeline installation', 'Watershed management'],
    activities: ['Check dam construction', 'Bore well drilling', 'Rainwater harvesting', 'Tank restoration', 'Pipeline installation'],
    stats: { villages: 320, schools: 90, volunteers: 4500, donations: 25000000 },
    stories: [
      { title: 'Community Check Dam', desc: 'New check dam restored water supply for 800 farming families.', img: '/hero/water.jpg' },
    ],
  },
  {
    id: 'agriculture-development',
    slug: 'agriculture-development',
    title: 'Agriculture Development',
    icon: '🌾',
    serviceKey: 'agriculture',
    color: 'bg-service-agriculture',
    lightColor: 'bg-service-agriculture-tint',
    textColor: 'text-service-agriculture',
    borderColor: 'border-service-agriculture',
    heroImage: '/hero/agriculture.jpg',
    cover: '/hero/agriculture.jpg',
    description: 'Supporting farmers with modern techniques, equipment, market linkages, and training programs.',
    longDescription: 'Modern farming training, organic practices, FPO formation, and direct market linkages — helping farmers increase yield and income sustainably.',
    impact: ['8,500+ farmers helped', '25% yield increase', '120+ FPOs formed'],
    objectives: ['Modern farming training', 'Equipment access', 'Organic farming promotion', 'Market linkages', 'Crop insurance awareness'],
    activities: ['Modern farming training', 'Equipment distribution', 'Organic farming', 'Market linkages', 'Crop insurance awareness'],
    stats: { villages: 280, schools: 0, volunteers: 5600, donations: 18000000 },
    stories: [
      { title: 'Farmer Producer Organisation', desc: '120 FPOs formed connecting 8,500 farmers to better markets.', img: '/hero/agriculture.jpg' },
    ],
  },
  {
    id: 'women-shgs',
    slug: 'women-shgs',
    title: 'Women SHGs',
    icon: '👩‍👩‍👧',
    serviceKey: 'women',
    color: 'bg-service-women',
    lightColor: 'bg-service-women-tint',
    textColor: 'text-service-women',
    borderColor: 'border-service-women',
    heroImage: '/hero/women.jpg',
    cover: '/hero/women.jpg',
    description: 'Empowering rural women through self-help groups, micro-finance, skill development, and entrepreneurship.',
    longDescription: 'SHG formation, skill training, micro-loans, and market access — enabling women to achieve financial independence and community leadership.',
    impact: ['2,400+ SHGs supported', '45,000+ women benefited', '₹3Cr micro-loans'],
    objectives: ['SHG formation & training', 'Micro-finance facilitation', 'Skill development', 'Market access', 'Leadership programs'],
    activities: ['SHG formation', 'Skill training', 'Micro-finance facilitation', 'Market access', 'Leadership programs'],
    stats: { villages: 240, schools: 60, volunteers: 2800, donations: 30000000 },
    stories: [
      { title: 'Women Leading Change', desc: '45 women formed SHGs and started micro-enterprises in Warangal district.', img: '/hero/women.jpg' },
    ],
  },
  {
    id: 'skill-development',
    slug: 'skill-development',
    title: 'Skill Development',
    icon: '🎓',
    serviceKey: 'skill',
    color: 'bg-service-skill',
    lightColor: 'bg-service-skill-tint',
    textColor: 'text-service-skill',
    borderColor: 'border-service-skill',
    heroImage: '/hero/skill.jpg',
    cover: '/hero/skill.jpg',
    description: 'Youth skill development, vocational training, and employment generation programs.',
    longDescription: 'Vocational courses aligned to market demand — computer literacy, trades, entrepreneurship — placing rural youth in sustainable employment.',
    impact: ['12,000+ youth trained', '8,500+ employed', '45+ trade courses'],
    objectives: ['Vocational training', 'Computer literacy', 'Job placement support', 'Entrepreneurship courses', 'Industry partnerships'],
    activities: ['Vocational training', 'Computer literacy', 'English communication', 'Entrepreneurship courses', 'Apprenticeship programs'],
    stats: { villages: 180, schools: 120, volunteers: 1900, donations: 12000000 },
    stories: [
      { title: 'Youth IT Training', desc: '100 rural youth completed digital skills training and secured local jobs.', img: '/hero/skill.jpg' },
    ],
  },
  {
    id: 'healthcare',
    slug: 'healthcare',
    title: 'Healthcare',
    icon: '🏥',
    serviceKey: 'healthcare',
    color: 'bg-service-healthcare',
    lightColor: 'bg-service-healthcare-tint',
    textColor: 'text-service-healthcare',
    borderColor: 'border-service-healthcare',
    heroImage: '/hero/healthcare.jpg',
    cover: '/hero/healthcare.jpg',
    description: 'Primary healthcare access, medical camps, disease prevention, and health awareness for rural communities.',
    longDescription: 'Free medical camps, vaccination drives, maternal health, and nutrition programs — bringing healthcare to the doorsteps of remote villages.',
    impact: ['250+ medical camps', '85,000+ patients served', '40+ PHCs supported'],
    objectives: ['Regular medical camps', 'Health awareness drives', 'Vaccination programs', 'Nutrition support', 'Mental health awareness'],
    activities: ['Medical camps', 'Health awareness', 'Vaccination drives', 'Nutrition programs', 'Mental health support'],
    stats: { villages: 250, schools: 80, volunteers: 4200, donations: 22000000 },
    stories: [
      { title: 'Village Health Camp', desc: '850 villagers received free check-ups and medicines in a single camp.', img: '/hero/healthcare.jpg' },
    ],
  },
];

/** Legacy slugs from older static data or bookmarks */
const SLUG_ALIASES = {
  'school-development': 'school-empowerment',
  agriculture: 'agriculture-development',
  'women-shg': 'women-shgs',
};

export function getProgramBySlug(slug) {
  const resolved = SLUG_ALIASES[slug] || slug;
  return PROGRAMS.find((p) => p.slug === resolved || p.id === resolved);
}

export const HERO_SLIDES = PROGRAMS.map((p) => ({
  src: p.heroImage,
  label: p.title,
  slug: p.slug,
}));
