/** Central admin route paths — use these instead of hardcoding `/admin` URLs. */
export const ADMIN_BASE = '/admin';

export const adminRoutes = {
  login: `${ADMIN_BASE}/login`,
  dashboard: ADMIN_BASE,
  navigation: `${ADMIN_BASE}/navigation`,
  pages: `${ADMIN_BASE}/pages`,
  homepage: `${ADMIN_BASE}/homepage`,
  activeWorks: `${ADMIN_BASE}/active-works`,
  teams: `${ADMIN_BASE}/teams`,
  partners: `${ADMIN_BASE}/partners`,
  beneficiaries: `${ADMIN_BASE}/beneficiaries`,
  gallery: `${ADMIN_BASE}/gallery`,
  users: `${ADMIN_BASE}/users`,
  memberDirectory: `${ADMIN_BASE}/member-directory`,
  volunteers: `${ADMIN_BASE}/volunteers`,
  villages: `${ADMIN_BASE}/villages`,
  villageActivities: `${ADMIN_BASE}/village-activities`,
  villageDonations: `${ADMIN_BASE}/village-donations`,
  schools: `${ADMIN_BASE}/schools`,
  schoolActivities: `${ADMIN_BASE}/school-activities`,
  schoolDonations: `${ADMIN_BASE}/school-donations`,
  projects: `${ADMIN_BASE}/projects`,
  projectCategories: `${ADMIN_BASE}/project-categories`,
  impactMetrics: `${ADMIN_BASE}/impact-metrics`,
  donations: `${ADMIN_BASE}/donations`,
  receipts: `${ADMIN_BASE}/receipts`,
  programs: `${ADMIN_BASE}/programs`,
  stories: `${ADMIN_BASE}/stories`,
  events: `${ADMIN_BASE}/events`,
  news: `${ADMIN_BASE}/news`,
  messages: `${ADMIN_BASE}/messages`,
  notifications: `${ADMIN_BASE}/notifications`,
  cms: `${ADMIN_BASE}/cms`,
  reports: `${ADMIN_BASE}/reports`,
  settings: `${ADMIN_BASE}/settings`,
  roles: `${ADMIN_BASE}/roles`,
  auditLogs: `${ADMIN_BASE}/audit-logs`,
  backup: `${ADMIN_BASE}/backup`,
};
